@startsalt
{+
  <b>Публикация нового груза</b>
  ---
  {
    <b>Маршрут</b>
    Откуда: | "Введите адрес погрузки...    "
    Куда:   | "Введите адрес выгрузки...    "
  }
  ---
  {
    <b>Параметры груза</b>
    Вес (т):       | "0    "
    Объем (м3):    | "0    "
    Тип кузова:    | ^Выберите тип кузова^
  }
  ---
  {
    <b>Ставка</b>
    <i>Заполните маршрут и вес для расчета...</i>
    Ставка (₽): | "0         " 
  }
  ---
  [ Отмена ] | [ <b>Опубликовать (заблокировано)</b> ]
}
@endsalt
