@startsalt
{+
  <b>Публикация нового груза</b>
  ---
  {
    <b>Маршрут</b>
    Откуда: | "Москва, ул. Ленина, 1      "
    Куда:   | "Санкт-Петербург, Невский 2 "
  }
  ---
  {
    <b>Параметры груза</b>
    Вес (т):       | "20   "
    Объем (м3):    | "82   "
    Тип кузова:    | ^Тент (Стандарт)^
  }
  ---
  {
    <b>Ставка</b>
    <color:green>Рекомендуемая ставка: 110 000 – 125 000 ₽</color>
    Ставка (₽): | "115000    "
  }
  ---
  [ Отмена ] | [ Сохранить черновик ] | [ <b>Опубликовать груз</b> ]
}
@endsalt
