@startsalt
{+
  <b>Публикация нового груза</b>
  ---
  {
    <b>Маршрут</b>
    Откуда: | "Москва, ул. Ленина, 1      "
    Куда:   | "Санкт-Петербург, Невский 2 "
  }
  ---
  {
    <b>Параметры груза</b>
    Вес (т):       | "20   "
    Объем (м3):    | "82   "
    Тип кузова:    | ^Тент (Стандарт)^
  }
  ---
  {
    <b>Ставка</b>
    <color:blue><i>Считаем рекомендованную ставку... (Spinner)</i></color>
    Ставка (₽): | "0         "
  }
  ---
  [ Отмена ] | [ <b>Опубликовать (заблокировано)</b> ]
}
@endsalt
