@startsalt
{+
  <b>Диспетчерский пульт (Active Fleet)</b>
  ---
  {
    <b>Список рейсов</b> | <b>Карта (Алерт!)</b>
    <color:red>[АВАРИЯ] Рейс #14</color>        | [ Карта отцентрирована на #14 ]
    <color:green>[В графике] Рейс #12</color>   | ---
    <color:green>[В графике] Рейс #15</color>   | <b>Действия по Рейсу #14:</b>
                               | [ Звонок водителю ]
                               | [ Назначить резерв ]
  }
}
@endsalt
