@startsalt
{+
  <b>Диспетчерский пульт (Active Fleet)</b>
  ---
  {
    <b>Список рейсов</b> | <b>Карта (GPS Телеметрия)</b>
    <color:green>[В графике] Рейс #12</color>   | [ Карта: Все машины ]
    <color:green>[В графике] Рейс #14</color>   | [ зеленые маркеры   ]
    <color:green>[В графике] Рейс #15</color>   | [ движутся штатно   ]
  }
}
@endsalt
