@startsalt
{+
  <b>Поиск грузов</b>
  ---
  {
    <b>Фильтры</b> | <b>Результаты (Найдено: 124)</b>
    [X] Тент     | [ Москва -> СПБ | 20т | 110 000 ₽ ]
    [] Рефриж.   | [ Казань -> Уфа | 10т | 45 000 ₽  ]
    Радиус: 50км | [ Самара -> МСК | 20т | 95 000 ₽  ]
  }
}
@endsalt
