@startsalt
{+
  <b>Поиск грузов</b>
  ---
  {
    <b>Фильтры</b> | <color:white><back:blue> Показать +3 новых груза </back></color>
    [X] Тент     | <b>Результаты (Найдено: 124)</b>
    [] Рефриж.   | [ Москва -> СПБ | 20т | 110 000 ₽ ]
    Радиус: 50км | [ Казань -> Уфа | 10т | 45 000 ₽  ]
                 | [ Самара -> МСК | 20т | 95 000 ₽  ]
  }
}
@endsalt
