@startsalt
{+
  <b>Отклики на груз #1005</b> (Статус: Опубликован)
  ---
  {
    <b>ООО Транс (4.8*)</b> | Предлагает: 100 000 ₽
    [ Принять ] | [ Встречное предложение ] | [ Отклонить ]
  }
  ---
  {
    <b>ИП Иванов (4.9*)</b> | Предлагает: 95 000 ₽
    [ Принять ] | [ Встречное предложение ] | [ Отклонить ]
  }
}
@endsalt
