@startsalt
{+
  <b>Отклики на груз #1005</b> (Статус: Забронирован)
  ---
  {
    <color:green><b>ИП Иванов (4.9*) - ПОБЕДИТЕЛЬ</b></color> | Согласовано: 95 000 ₽
    [ <b>Перейти к Договору-заявке</b> ]
  }
  ---
  {
    <color:gray><b>ООО Транс (4.8*)</b></color> | <color:gray>Груз отдан другому</color>
    <color:gray>[ Принять ]</color> | <color:gray>[ Встречное предложение ]</color> | <color:gray>[ Отклонить ]</color>
  }
}
@endsalt
