@startsalt
{+
  <b>Дашборд грузовладельца</b>
  ---
  {
    <b>Сводка</b>
    Активные грузы: | "12"
    Рейсы в пути:   | <color:orange>"5 (1 задерживается)"</color>
    К оплате:       | <color:red>"340 000 ₽"</color>
  }
  ---
  [ <b>Создать груз</b> ] | [ Мои шаблоны ]
  ---
  <b>Лента активности</b>
  * 14:30 | Груз #1002 доставлен (ожидает документы)
  * 14:15 | Поступил новый отклик на груз #1004 (90 000 ₽)
  * 12:00 | Водитель Иванов прибыл на погрузку
}
@endsalt
