@startsalt
{+
  <b>Дашборд грузовладельца</b>
  ---
  {
    <b>Сводка (Loading...)</b>
    Активные грузы: | "..."
    Рейсы в пути:   | "..."
    К оплате:       | "..."
  }
  ---
  [ Создать груз ] | [ Мои шаблоны ]
  ---
  <b>Лента активности</b>
  <i>Загрузка последних событий... (Spinner)</i>
}
@endsalt
